# Generated by Django 3.2.8 on 2021-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_maindoctor_doctor_zam'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_age',
            field=models.CharField(default=20, max_length=50),
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='doctor_age',
            field=models.CharField(default=20, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_pasient',
            field=models.CharField(default=20, max_length=200),
        ),
        migrations.AlterField(
            model_name='maindoctor',
            name='doctor_pasient',
            field=models.CharField(default=20, max_length=200),
        ),
    ]
