# Generated by Django 3.2.8 on 2021-10-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_work', models.CharField(max_length=100)),
                ('doctor_experience', models.CharField(max_length=100)),
                ('doctor_number', models.CharField(max_length=100)),
                ('doctor_pasient', models.CharField(max_length=200)),
                ('doctor_zam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maindoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_work', models.CharField(max_length=100)),
                ('doctor_experience', models.CharField(max_length=100)),
                ('doctor_number', models.CharField(max_length=100)),
                ('doctor_pasient', models.CharField(max_length=200)),
                ('doctor_zam', models.CharField(max_length=100)),
            ],
        ),
    ]
