# Generated by Django 3.2.8 on 2021-10-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211015_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_name', models.CharField(max_length=20)),
                ('nurse_pincode', models.CharField(max_length=9)),
                ('nurse_age', models.CharField(max_length=4)),
                ('nurse_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_pincode', models.CharField(max_length=9)),
                ('patient_age', models.CharField(max_length=5)),
                ('patient_number', models.CharField(max_length=15)),
            ],
        ),
    ]
