# Generated by Django 3.2.8 on 2021-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_nurse_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindoctor',
            name='doctor_pasient',
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='doctor_pincode',
            field=models.CharField(default=123134, max_length=15),
        ),
    ]
